# This is a config for E2B sandbox template.
# You can use template ID (8hyxcs5leb5crrr4aeh7) or template name (nhung-builder-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nhung-builder-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("nhung-builder-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nhung-builder-2')

team_id = "9361c25e-1812-47bb-bc64-d0c547a88201"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nhung-builder-2"
template_id = "8hyxcs5leb5crrr4aeh7"
